version: '3'

services:
  mwc-2:
    container_name: mwc-2
    hostname: mwc-2
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/mwc-2/app
